[package]
name = "grid_server_interface"
version = "0.1.0"
authors = ["Lennart Kudling"]
edition = "2021"

[dependencies]
prost = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = "0.9.2"
