[package]
name = "grid_manager_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = { workspace = true }
grid_manager_interface = { path= "../lib_interface_grid_manager" }
log = { workspace = true }
tokio = { workspace = true }
