[package]
name = "grid-control"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = { workspace = true }
grid_client = { path= "../lib_grid_client" }
grid_server_interface = { path= "../lib_grid_server_interface" }
log = { workspace = true }
tokio = { workspace = true }
